var conventions =
[
    [ "Readability", "d2/d4c/readability.html", [
      [ "readability-identifier-naming", "d2/d4c/readability.html#autotoc_md82", null ],
      [ "readability-avoid-const-params-in-decls", "d2/d4c/readability.html#autotoc_md83", null ],
      [ "readability-avoid-nested-conditional-operator", "d2/d4c/readability.html#autotoc_md84", null ],
      [ "readability-avoid-return-with-void-value", "d2/d4c/readability.html#autotoc_md85", null ],
      [ "readability-avoid-unconditional-preprocessor-if", "d2/d4c/readability.html#autotoc_md86", null ],
      [ "readability-const-return-type", "d2/d4c/readability.html#autotoc_md87", null ],
      [ "readability-container-contains", "d2/d4c/readability.html#autotoc_md88", null ],
      [ "readability-container-data-pointer", "d2/d4c/readability.html#autotoc_md89", null ],
      [ "readability-container-size-empty", "d2/d4c/readability.html#autotoc_md90", null ],
      [ "readability-delete-null-pointer", "d2/d4c/readability.html#autotoc_md91", null ],
      [ "readability-duplicate-include", "d2/d4c/readability.html#autotoc_md92", null ],
      [ "readability-else-after-return", "d2/d4c/readability.html#autotoc_md93", null ],
      [ "readability-enum-initial-value", "d2/d4c/readability.html#autotoc_md94", null ],
      [ "readability-function-size", "d2/d4c/readability.html#autotoc_md95", null ],
      [ "readability-inconsistent-declaration-parameter-name", "d2/d4c/readability.html#autotoc_md96", null ],
      [ "readability-make-member-function-const", "d2/d4c/readability.html#autotoc_md97", null ],
      [ "readability-math-missing-parentheses", "d2/d4c/readability.html#autotoc_md98", null ],
      [ "readability-misleading-indentation", "d2/d4c/readability.html#autotoc_md99", null ],
      [ "readability-misplaced-array-index", "d2/d4c/readability.html#autotoc_md100", null ],
      [ "readability-non-const-parameter", "d2/d4c/readability.html#autotoc_md101", null ],
      [ "readability-qualified-auto", "d2/d4c/readability.html#autotoc_md102", null ],
      [ "readability-redundant-casting", "d2/d4c/readability.html#autotoc_md103", null ],
      [ "readability-redundant-control-flow", "d2/d4c/readability.html#autotoc_md104", null ],
      [ "readability-redundant-declaration", "d2/d4c/readability.html#autotoc_md105", null ],
      [ "readability-redundant-inline-specifier", "d2/d4c/readability.html#autotoc_md106", null ],
      [ "readability-redundant-member-init", "d2/d4c/readability.html#autotoc_md107", null ],
      [ "readability-redundant-preprocessor", "d2/d4c/readability.html#autotoc_md108", null ],
      [ "readability-redundant-smartptr-get", "d2/d4c/readability.html#autotoc_md109", null ],
      [ "readability-redundant-string-cstr", "d2/d4c/readability.html#autotoc_md110", null ],
      [ "readability-redundant-string-init", "d2/d4c/readability.html#autotoc_md111", null ],
      [ "readability-reference-to-constructed-temporary", "d2/d4c/readability.html#autotoc_md112", null ],
      [ "readability-simplify-boolean-expr", "d2/d4c/readability.html#autotoc_md113", null ],
      [ "readability-simplify-subscript-expr", "d2/d4c/readability.html#autotoc_md114", null ],
      [ "readability-static-accessed-through-instance", "d2/d4c/readability.html#autotoc_md115", null ],
      [ "readability-static-definition-in-anonymous-namespace", "d2/d4c/readability.html#autotoc_md116", null ],
      [ "readability-string-compare", "d2/d4c/readability.html#autotoc_md117", null ],
      [ "readability-use-std-min-max", "d2/d4c/readability.html#autotoc_md118", null ]
    ] ],
    [ "Modernize", "d5/da7/modernize.html", [
      [ "modernize-avoid-bind", "d5/da7/modernize.html#autotoc_md50", null ],
      [ "modernize-avoid-c-arrays", "d5/da7/modernize.html#autotoc_md51", null ],
      [ "modernize-concat-nested-namespaces", "d5/da7/modernize.html#autotoc_md52", null ],
      [ "modernize-deprecated-headers", "d5/da7/modernize.html#autotoc_md53", null ],
      [ "modernize-deprecated-ios-base-aliases", "d5/da7/modernize.html#autotoc_md54", null ],
      [ "modernize-loop-convert", "d5/da7/modernize.html#autotoc_md55", null ],
      [ "modernize-macro-to-enum", "d5/da7/modernize.html#autotoc_md56", null ],
      [ "modernize-make-shared", "d5/da7/modernize.html#autotoc_md57", null ],
      [ "modernize-make-unique", "d5/da7/modernize.html#autotoc_md58", null ],
      [ "modernize-min-max-use-initializer-list", "d5/da7/modernize.html#autotoc_md59", null ],
      [ "modernize-raw-string-literal", "d5/da7/modernize.html#autotoc_md60", null ],
      [ "modernize-redundant-void-arg", "d5/da7/modernize.html#autotoc_md61", null ],
      [ "modernize-replace-random-shuffle", "d5/da7/modernize.html#autotoc_md62", null ],
      [ "modernize-return-braced-init-list", "d5/da7/modernize.html#autotoc_md63", null ],
      [ "modernize-type-traits", "d5/da7/modernize.html#autotoc_md64", null ],
      [ "modernize-use-bool-literals", "d5/da7/modernize.html#autotoc_md65", null ],
      [ "modernize-use-constraints", "d5/da7/modernize.html#autotoc_md66", null ],
      [ "modernize-use-equals-default", "d5/da7/modernize.html#autotoc_md67", null ],
      [ "modernize-use-equals-delete", "d5/da7/modernize.html#autotoc_md68", null ],
      [ "modernize-use-default-member-init", "d5/da7/modernize.html#autotoc_md69", null ],
      [ "modernize-use-emplace", "d5/da7/modernize.html#autotoc_md70", null ],
      [ "modernize-use-integer-sign-comparison", "d5/da7/modernize.html#autotoc_md71", null ],
      [ "modernize-use-nodiscard", "d5/da7/modernize.html#autotoc_md72", null ],
      [ "modernize-use-noexcept", "d5/da7/modernize.html#autotoc_md73", null ],
      [ "modernize-use-nullptr", "d5/da7/modernize.html#autotoc_md74", null ],
      [ "modernize-use-override", "d5/da7/modernize.html#autotoc_md75", null ],
      [ "modernize-use-ranges", "d5/da7/modernize.html#autotoc_md76", null ],
      [ "modernize-use-std-format", "d5/da7/modernize.html#autotoc_md77", null ],
      [ "modernize-use-std-numbers", "d5/da7/modernize.html#autotoc_md78", null ],
      [ "modernize-use-std-print", "d5/da7/modernize.html#autotoc_md79", null ],
      [ "modernize-use-uncaught-exceptions", "d5/da7/modernize.html#autotoc_md80", null ],
      [ "modernize-use-using", "d5/da7/modernize.html#autotoc_md81", null ]
    ] ],
    [ "Performance", "dc/d3c/performance.html", [
      [ "performance-avoid-endl", "dc/d3c/performance.html#autotoc_md20", null ],
      [ "performance-enum-size", "dc/d3c/performance.html#autotoc_md24", null ],
      [ "performance-faster-string-find", "dc/d3c/performance.html#autotoc_md28", null ],
      [ "performance-for-range-copy", "dc/d3c/performance.html#autotoc_md32", null ],
      [ "performance-implicit-conversion-in-loop", "dc/d3c/performance.html#autotoc_md36", null ],
      [ "performance-inefficient-algorithm", "dc/d3c/performance.html#autotoc_md40", null ],
      [ "performance-inefficient-vector-operation", "dc/d3c/performance.html#autotoc_md42", null ],
      [ "performance-move-const-arg", "dc/d3c/performance.html#autotoc_md44", null ],
      [ "performance-no-int-to-ptr", "dc/d3c/performance.html#autotoc_md45", null ],
      [ "performance-trivially-destructible", "dc/d3c/performance.html#autotoc_md46", null ],
      [ "performance-type-promotion-in-math-fn", "dc/d3c/performance.html#autotoc_md47", null ],
      [ "performance-unnecessary-copy-initialization", "dc/d3c/performance.html#autotoc_md48", null ],
      [ "performance-unnecessary-value-param", "dc/d3c/performance.html#autotoc_md49", null ]
    ] ],
    [ "Cppcoreguidelines", "df/da4/cppcore.html", [
      [ "cppcoreguidelines-avoid-goto", "df/da4/cppcore.html#autotoc_md4", null ],
      [ "cppcoreguidelines-init-variables", "df/da4/cppcore.html#autotoc_md5", null ],
      [ "cppcoreguidelines-no-malloc", "df/da4/cppcore.html#autotoc_md6", null ],
      [ "cppcoreguidelines-prefer-member-initializer", "df/da4/cppcore.html#autotoc_md7", null ],
      [ "cppcoreguidelines-pro-type-cstyle-cast", "df/da4/cppcore.html#autotoc_md8", null ],
      [ "cppcoreguidelines-pro-type-member-init", "df/da4/cppcore.html#autotoc_md9", null ],
      [ "cppcoreguidelines-pro-type-static-cast-downcast", "df/da4/cppcore.html#autotoc_md10", null ]
    ] ],
    [ "Misc", "d8/d0b/misc.html", [
      [ "misc-header-include-cycle", "d8/d0b/misc.html#autotoc_md1", null ],
      [ "misc-throw-by-value-catch-by-reference", "d8/d0b/misc.html#autotoc_md2", null ]
    ] ],
    [ "Bugprone", "db/d22/bugprone.html", [
      [ "bugprone-assert-side-effect", "db/d22/bugprone.html#autotoc_md11", null ],
      [ "bugprone-branch-clone", "db/d22/bugprone.html#autotoc_md12", null ],
      [ "bugprone-casting-through-void", "db/d22/bugprone.html#autotoc_md13", null ],
      [ "bugprone-compare-pointer-to-member-virtual-function", "db/d22/bugprone.html#autotoc_md14", null ],
      [ "bugprone-copy-constructor-init", "db/d22/bugprone.html#autotoc_md15", null ],
      [ "bugprone-crtp-constructor-accessibility", "db/d22/bugprone.html#autotoc_md16", null ],
      [ "bugprone-empty-catch", "db/d22/bugprone.html#autotoc_md17", null ],
      [ "bugprone-exception-escape", "db/d22/bugprone.html#autotoc_md18", null ],
      [ "bugprone-forward-declaration-namespace", "db/d22/bugprone.html#autotoc_md19", null ],
      [ "bugprone-inaccurate-erase", "db/d22/bugprone.html#autotoc_md21", null ],
      [ "bugprone-incorrect-roundings", "db/d22/bugprone.html#autotoc_md23", null ],
      [ "bugprone-infinite-loop", "db/d22/bugprone.html#autotoc_md25", null ],
      [ "bugprone-integer-division", "db/d22/bugprone.html#autotoc_md26", null ],
      [ "bugprone-lambda-function-name", "db/d22/bugprone.html#autotoc_md27", null ],
      [ "bugprone-macro-parentheses", "db/d22/bugprone.html#autotoc_md29", null ],
      [ "bugprone-move-forwarding-reference", "db/d22/bugprone.html#autotoc_md31", null ],
      [ "bugprone-parent-virtual-call", "db/d22/bugprone.html#autotoc_md33", null ],
      [ "bugprone-redundant-branch-condition", "db/d22/bugprone.html#autotoc_md34", null ],
      [ "bugprone-standalone-empty", "db/d22/bugprone.html#autotoc_md35", null ],
      [ "bugprone-too-small-loop-variable", "db/d22/bugprone.html#autotoc_md37", null ],
      [ "bugprone-unsafe-functions", "db/d22/bugprone.html#autotoc_md38", null ],
      [ "bugprone-use-after-move", "db/d22/bugprone.html#autotoc_md39", null ],
      [ "bugprone-virtual-near-miss", "db/d22/bugprone.html#autotoc_md41", null ]
    ] ]
];